/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as daoPointSol from "./DAOPoint.sol";
export type { daoPointSol };
import type * as midpointSol from "./Midpoint.sol";
export type { midpointSol };
import type * as boilerSol from "./boiler.sol";
export type { boilerSol };
import type * as governanceStandard from "./governance_standard";
export type { governanceStandard };
import type * as optional from "./optional";
export type { optional };
export type { Box } from "./Box";
export type { GovernanceToken } from "./GovernanceToken";
