/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as governorContractSol from "./GovernorContract.sol";
export { TimeLock__factory } from "./TimeLock__factory";
