/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMidpoint__factory } from "./IMidpoint__factory";
export { SampleContract__factory } from "./SampleContract__factory";
