/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governorContractSol from "./GovernorContract.sol";
export type { governorContractSol };
export type { TimeLock } from "./TimeLock";
